<?xml version="1.0" encoding="utf-8"?>
<Database Name="RoomReservation" EntityNamespace="Wrox.ProCSharp.WCF.Entities" ContextNamespace="Wrox.ProCSharp.WCF.Data" Class="RoomReservationDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=RoomReservation;Integrated Security=True" SettingsObjectName="Wrox.ProCSharp.WCF.Properties.Settings" SettingsPropertyName="RoomReservationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RoomReservations" Member="RoomReservations">
    <Type Name="RoomReservation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoomName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Event" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>