<?xml version="1.0" encoding="utf-16"?>
<Database Name="ProCSharp" Class="ProCSharpDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=ProCSharp;Integrated Security=True;Pooling=False" SettingsObjectName="LinqClient.Properties.Settings" SettingsPropertyName="ProCSharpConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Exams" Member="Exams">
    <Type Name="Exam">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Info" Type="System.Xml.Linq.XDocument" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>